### ISSUE TITLE
Apple Music not working on macOS Sonoma

### ISSUE THREAD

**Issue by iKL3W** [inedible-dev/MusicBar#23]
The menu item doesn't detect when I play music from Music on macOS Sonoma.

**Comment by Kentakoong** [comment]
Could you provide a video of it not showing, the application that you're streaming from, and some more explanations when it happened?

**Comment by Kentakoong** [comment]
this doesn't seem right for now, so if you have any issues, please give more details and I'll be reopening this, thanks.
