### ISSUE TITLE
unreadable text at the unfocused display menubar

### ISSUE THREAD

**Issue by mintyleaf** [inedible-dev/MusicBar#8]
![image](https://user-images.githubusercontent.com/17470408/204113036-3939690d-2f32-4dee-b4cc-93d125ec88d9.png)

**Comment by mintyleaf** [comment]
and yeah, that album art tend to disappear after some time
![image](https://user-images.githubusercontent.com/17470408/204113197-d0d3a11f-7fab-4580-9a71-cc570a20115e.png)

looked trough the code - album art is actually just an button ui element icon, which is likely supposed to not to be at the center
maybe you just using another macOS version with different ui elements handling or idk

**Comment by Kentakoong** [comment]
Yep, saw someone commented this too. I'll try to figure what happened, and sort it out. But if you have some ideas how to fix this, it would be awesome!

**Comment by mintyleaf** [comment]
> But if you have some ideas how to fix this, it would be awesome!

firstly:
https://developer.apple.com/documentation/appkit/nscontrol/imageposition

you don't set it anywhere, so it fallbacks to something, which is right in your case, but not in mine (different macOS version or idk)

secondly:
not sure about "appearsDisabled", but maybe this is it:
https://developer.apple.com/documentation/appkit/nsstatusbarbutton
maybe this could help too:
https://developer.apple.com/documentation/uikit/uimenuelement/attributes

**Comment by mintyleaf** [comment]
not sure why image is "unavailable", according to the checkAvailability function, which is replacing it by rays
I'd prefer to have ♪ symbol instead of that rays spinner in that cases
or maybe after some timeout when it's clearly that something wrong with album art fetching

**Comment by Kentakoong** [comment]
> not sure why image is "unavailable", according to the checkAvailability function, which is replacing it by rays
> I'd prefer to have ♪ symbol instead of that rays spinner in that cases
> or maybe after some timeout when it's clearly that something wrong with album art fetching

yeah, this seems to be a good fit for the icon, will definitely edit that!

**Comment by Kentakoong** [comment]
edited that, could you try cloning the latest commit in [fix-status-bar](https://github.com/Kentakoong/MusicBar/tree/fix-status-bar)?

**Comment by mintyleaf** [comment]
yep, unreadable text is fixed

**Comment by mintyleaf** [comment]
![image](https://user-images.githubusercontent.com/17470408/204580484-bd96278c-c608-45e5-88b7-d862502dc6b4.png)
it's still occurring as soon, as actual album art is fetched (I opened video, and it was ok on the other screen until image is fetched)
for me album arts is loading mostly for YouTube, Spotify is remaining without it most of the time (but I remember that it actually worked few times, which is strange enough)
so yeah, seems like that fix applied only for non-image style

**Comment by Kentakoong** [comment]
<img width="415" alt="Screenshot 2022-11-30 at 8 14 04 AM" src="https://user-images.githubusercontent.com/35761701/204683464-cd0c6751-b959-42ad-b37e-9d5d4b368bc2.png">

yep, seems like a weird thing again. Mine doesn't show the art even. So I guess it's a Catalina problem again😥
I'll try to find a workaround

**Comment by Kentakoong** [comment]
I'll take a look at this in a later date, if it's still occurring, please open a new issue or tag me here!
